apiVersion: v1
kind: Namespace
metadata:
  name: foundry
---
apiVersion: v1
kind: Secret
metadata:
  name: foundry-creds
  namespace: foundry
type: kubernetes.io/basic-auth
stringData:
  username: "" # Replace this with your Foundry username
  password: "" # Replace this with your Foundry password